apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gokhankiziltepe.net
  dnsNames: 
    - gokhankiziltepe.net
    - www.gokhankiziltepe.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - gokhankiziltepe.net
          - www.gokhankiziltepe.net
